### ISSUE TITLE
Is there any way to customise the scanning range of event at a time?

### ISSUE THREAD

**Issue by xiaoch05** [enviodev/hyperindex#121]

**Comment by JonoPrest** [comment]
Hey @xiaoch05,

Yes there is, have a look at the config explorer on the docs:
https://docs.envio.dev/docs/HyperIndex/configuration-file#explorer

Under networks->rpc_config, there are a number of sync parameters you can set. What version of envio are you using?

**Comment by JonoPrest** [comment]
@xiaoch05 here are the docs for v2 rpc config:
https://docs.envio.dev/docs/HyperIndex/rpc-sync

And here they are for v1:
https://docs.envio.dev/docs/HyperIndex/v1/rpc-sync

What you are looking for "block interval" this is a dynamically changing value based on whether RPC has failures on range too big. So you probably want to reduce the `initial_block_interval`, `interval_ceiling` and `acceleration_additive` so that it doesn't increase in big steps on successes.

**Comment by moose-code** [comment]
Hi @xiaoch05 - please feel free to reopen if you have further questions :)
