### ISSUE TITLE
Contract Register event type obj has changed in v2.2.0

### ISSUE THREAD

**Issue by DenhamPreen** [enviodev/hyperindex#178]
**Describe the bug**

**To Reproduce**

clone https://github.com/hashscape/salt-dex-indexer

Steps to reproduce
change envio version to 2.2.0
pnpm install
pnpm envio dev

Add these logs to see the change in event type
```typescript
UniswapV2Factory.PairCreated.contractRegister(({ event, context }) => {

  console.log(`PairCreated: ${event.params}`)
  console.log(`PairCreated: ${event.params.pair}`)

...
});
```

**Expected behavior**

Event type to be an object

**Screenshots**

![image](https://github.com/user-attachments/assets/6dcea5f9-5747-45f6-83ef-a9160eb4f722)

**Local (please complete the following information):**

 - Envio version
  2.2.0

Thanks to @ chrisais9 for flagging

**Comment by DZakh** [comment]
@chrisais9 To fix the types in your indexer, you can change imports to the publicly exposed types. Compared to the internal `.gen.ts` files, they are officially maintained without breaking changes on minor released 👌

<img width="908" alt="image" src="https://github.com/user-attachments/assets/9b0611aa-b146-4079-b3a5-6020a2481ff4">

Also, regarding the bug, I managed to scope it out to changes in Viem decoding logic, it probably happened after upgrading the package. While I'm working on the fix, you can work around it by changing the event decoder to Envio's one. It should be event faster than the Viem one.

You can do this by removing the line in your config:

<img width="504" alt="image" src="https://github.com/user-attachments/assets/58a1f70f-27cd-41e6-b7a5-ec51df8f8c2a">

And I'll let you know when the issue is fixed for the Viem decoder if you want to continue using it.

**Comment by chrisais9** [comment]
@DZakh 
Okay
I will update my types to publicly exposed types. Also, use envio's one instead of viem.

**Comment by DZakh** [comment]
PR with a fix is ready https://github.com/enviodev/hyperindex/pull/180

We'll do a release when the tests finish successfully 👌

**Comment by DZakh** [comment]
Solved in https://github.com/enviodev/hyperindex/releases/tag/v2.2.2

Thanks, for reporting 🫡
