### ISSUE TITLE
Indexer freezes at a certain event count

### ISSUE THREAD

**Issue by TLGINO** [enviodev/hyperindex#183]
# Issue
Indexer stops indexing, does not throw any errors

# Steps to re-create:

Use envio 2.2.2 (or less, same problem occured)

```sh
git clone https://github.com/TLGINO/TornadoTrack
cd TornadoTrack/tornado_indexer
envio dev
```
The indexer will stop indexing at exactly 885,316 events processed

![problem](https://github.com/user-attachments/assets/2d427923-b5ab-435a-bfdb-4bee334e0a53)

I have tried on 2 machines and had the same result.

# Temp solution:
By commenting out all the chains except one, the indexer was able to sync
I would then repeat the process for all chains until they were all individually synced
Once all chains were individually synced I could un-comment all of config.yaml and was able to use the indexer normally (with all chains)

```sh
envio codegen
envio start
```
wait for chain to index, then switch chain and rinse and repeat

**Comment by JonoPrest** [comment]
Hey @TLGINO,

Sorry about the issue of it getting stuck! I've looked into it and it's an oversight in that Goerli (chain 5) has a finite end of the chain. 

The indexer tries to synchronise the processing of events across each chain. And since it reaches the head of Goerli, it's waiting for a new block to see which chain's events it should process first. A quick solution to your problem is to set `unordered_multichain_mode: true` in your config. See this doc for details about how it works: https://docs.envio.dev/docs/HyperIndex/multichain-indexing#unordered-multichain-mode

If the order of events processed between chains doesn't matter to you then this will be the recommended setting anyhow. I will close this issue once I've implemented a fix for this synchronisation mechanism that accounts for finite chains.
