### ISSUE TITLE
Check if all the events from `config.yaml` are handled

### ISSUE THREAD

**Issue by 0xkenj1** [enviodev/hyperindex#282]
**Describe the bug**
You can add many events to the config, but if you don't create a handler in `./src/handlers` for eachone, the event is not considered.

**To Reproduce**
1. Add an event to config.yaml
2. Run indexer
3. Check in that the event doesn't appear in `raw_events`

**Expected behavior**
Should at least warn that an event wasn't handled 

**Local (please complete the following information):**
 - envio@2.5.2
 - node@20
 - pnpm@9.9.0
 - docker@27.1.1

**Additional context**

I created this script for our project: https://gist.github.com/0xkenj1/3e6b3e7d9424c082e2d07b0764d8c03e

**Comment by JonoPrest** [comment]
Hey @0xkenj1,

Sorry for the late response, this one slipped passed!

This is actually expected behaviour. The raw events table contains all the events that have been fully processed by a handler.

If you follow our [quick start](https://docs.envio.dev/docs/HyperIndex/contract-import#enter-in-the-address-of-the-contract-to-import) using the contract import feature you can actually quickly generate an indexers that just capture's each event in it's own table.

We can also look at adding this capability as a feature (saving to raw events table without needing to register a handler)
